packages:
  - 'packages/*'

catalog:
  react: ^19.0.0
  react-dom: ^19.0.0
  "@types/react": ^19.0.0
  "@types/react-dom": ^19.0.0
  tailwindcss: ^3.4.17
  postcss: ^8.4.49
  autoprefixer: ^10.4.20
  "@fontsource/inter": "^5.1.0"
  "@fontsource/urbanist": "^5.1.1"
