packages:
  - 'packages/*'

catalog:
  class-variance-authority: ^0.7.1
  dayjs: ^1.11.13
  lodash: ^4.17.21
  '@types/lodash': ^4.17.15
  react: ^19.0.0
  react-dom: ^19.0.0
  '@types/react': ^19.0.0
  '@types/react-dom': ^19.0.0
  tailwindcss: ^3.4.17
  tailwind-merge: ^2.6.0
  postcss: ^8.4.49
  "pluralize": "^8.0.0"
  "@types/pluralize": "^0.0.33"
  autoprefixer: ^10.4.20
  '@fontsource/inter': '^5.1.0'
  '@fontsource/urbanist': '^5.1.1'
  'vite-plugin-svgr': '^4.3.0'
  'vitest': '^3.0.7'
  'dayjs': '^1.11.13'
