packages:
  - 'packages/*'

catalog:
  '@fontsource/inter': '^5.1.0'
  '@fontsource/urbanist': '^5.1.1'
  '@types/lodash': ^4.17.15
  '@types/pluralize': '^0.0.33'
  '@types/react-dom': ^19.0.0
  '@types/react': ^19.0.0
  'pluralize': '^8.0.0'
  'vite-plugin-svgr': '^4.3.0'
  'vitest': '^3.0.7'
  autoprefixer: ^10.4.20
  class-variance-authority: ^0.7.1
  dayjs: ^1.11.13
  lodash: ^4.17.21
  postcss: ^8.4.49
  react-dom: ^19.0.0
  react: ^19.0.0
  tailwind-merge: ^2.6.0
  tailwindcss: ^3.4.17
