name: CI workflow

on:
  pull_request:
    branches:
      - "develop"
      - "release_*"

jobs:
  checks:
    name: Check
    runs-on: ubuntu-latest

    steps:
      - name: Git checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Install pnpm
        uses: pnpm/action-setup@903f9c1a6ebcba6cf41d87230be49611ac97822e # v6.0.3

      - name: Use Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: 24.15.0
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Run TypeScript check
        run: pnpm tsc

      - name: Run Prettier check
        run: pnpm prettier

      - name: Run ESLint check
        run: pnpm eslint

  builds:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Git checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Install pnpm
        uses: pnpm/action-setup@903f9c1a6ebcba6cf41d87230be49611ac97822e # v6.0.3

      - name: Use Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: 24.15.0
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Build UI Library
        run: pnpm ui-library:build

      - name: Build Web App
        run: pnpm web-app:build

      - name: Build Keycloak Login
        run: pnpm keycloak-login:build

      - name: Copy Keycloak Login Output
        run: pnpm keycloak-login:copy-output

  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Git checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Install pnpm
        uses: pnpm/action-setup@903f9c1a6ebcba6cf41d87230be49611ac97822e # v6.0.3

      - name: Use Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: 24.15.0
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Run unit test in web-app
        run: pnpm web-app:test
